export const stateNames: Record<string, boolean> = {
    "ALABAMA": true,
    "ALASKA": true,
    "ARIZONA": true,
    "ARKANSAS": true,
    "CALIFORNIA": true,
    "COLORADO": true,
    "CONNECTICUT": true,
    "DELAWARE": true,
    "FLORIDA": true,
    "GEORGIA": true,
    "HAWAII": true,
    "IDAHO": true,
    "ILLINOIS": true,
    "INDIANA": true,
    "IOWA": true,
    "KANSAS": true,
    "KENTUCKY": true,
    "LOUISIANA": true,
    "MAINE": true,
    "MARYLAND": true,
    "MASSACHUSETTS": true,
    "MICHIGAN": true,
    "MINNESOTA": true,
    "MISSISSIPPI": true,
    "MISSOURI": true,
    "MONTANA": true,
    "NEBRASKA": true,
    "NEVADA": true,
    "NEW HAMPSHIRE": true,
    "NEW JERSEY": true,
    "NEW MEXICO": true,
    "NEW YORK": true,
    "NORTH CAROLINA": true,
    "NORTH DAKOTA": true,
    "OHIO": true,
    "OKLAHOMA": true,
    "OREGON": true,
    "PENNSYLVANIA": true,
    "RHODE ISLAND": true,
    "SOUTH CAROLINA": true,
    "SOUTH DAKOTA": true,
    "TENNESSEE": true,
    "TEXAS": true,
    "UTAH": true,
    "VERMONT": true,
    "VIRGINIA": true,
    "WASHINGTON": true,
    "WEST VIRGINIA": true,
    "WISCONSIN": true,
    "WYOMING": true
};